version: "3.9"

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"   # AWS API Gateway
    environment:
      - SERVICES=s3,ec2,iam,lambda,rds,sns,sqs
      - DEBUG=1
    volumes:
      - "./.localstack:/var/lib/localstack"

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rds_mock
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

